name = "raspberry_bsp"
description = "Board Support package for Raspberry PI v1, v2 and B+"
version = "1.0.0"

authors = ["Tama McGlinn"]
maintainers = ["Tama McGlinn <t.mcglinn@gmail.com>"]
maintainers-logins = ["TamaMcGlinn"]

licenses = "MIT"
tags = ["raspberry", "pi"]
website = "https://github.com/TamaMcGlinn/ada_raspio"

[origin]
commit = "07ec9ffc0e79086f162d0a420d6d20f366020eec"
url = "git+https://github.com/TamaMcGlinn/ada_raspio.git"

